adjusted test outcome logic

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -69,7 +69,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       # Define an output for the job
-      final_result: ${{ steps.verify-failure.conclusion == 'success' && steps.verify-not-failure.conclusion != 'success'}}
+      test_result: ${{ steps.negative-tests-outcome.outcome }}
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -116,6 +116,13 @@ jobs:
           echo "steps.test-no-return.outcome = ${{ steps.test-no-return.outcome }}"
           echo "steps.test-return-non-string.outcome = ${{ steps.test-return-non-string.outcome }}"
 
+          if(steps.test-no-return.outcome == 'failure' && steps.test-return-non-string.outcome == 'failure'){
+            echo "✅ All negative tests failed as expected."
+          } else {
+            echo "❌ One or more expected negative tests did not fail."
+            exit 1
+          }
+
   test-summary:
     name: Test Summary
     runs-on: ubuntu-latest
@@ -134,6 +141,6 @@ jobs:
                 + "| Check | Status |\n"
                 + "|-------|--------|\n"
                 + "| Lint & Test | ${{ needs.lint-and-test.result == 'success' && '✅ Passed' || '❌ Failed' }} |\n"
-                + "| Negative Test | ${{ needs.negative-tests.outputs.final_result == 'success' && '✅ Passed' || '❌ Failed' }} |\n\n";
+                + "| Negative Test | ${{ needs.negative-tests.outputs.test_result == 'success' && '✅ Passed' || '❌ Failed' }} |\n\n";
 
             return body;
